default_stages: [commit, manual]

repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-added-large-files
        args: [--maxkb=5000]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          [
            --max-line-length=100,
            "--per-file-ignores=__init__.py:F401",
            "--ignore=E203,E402,E501,W503,F821,C901,E266",
          ]

  - repo: https://github.com/ambv/black
    rev: 23.12.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=80]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: poetry run pytest
        language: system
        pass_filenames: false
        always_run: true
