on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install black, flake8 and isort
        run: python -m pip install black flake8 isort
      - name: Run linting
        run: |
          flake8 --max-line-length=100 --per-file-ignores="__init__.py:F401" --ignore="E203,E402,E501,W503,F821,C901,E266"
          black . --line-length=80 --check
          isort .

  install:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install project
        run: |
          poetry config http-basic.finfrog ${{ secrets.FINFROG_REPO_USER }} "${{ secrets.FINFROG_REPO_PASSWORD }}"
          poetry install --no-interaction
